version: "3.7"
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: ${APP_POSTGRES_DB}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}

  redis:
    image: redis:6
    ports:
      - 6379:6379