name: Build

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: golang-1.14
    steps:
      #
      #    - name: Set up Go 1.x
      #      uses: actions/setup-go@v2
      #      with:
      #        go-version: ^1.14
      #      id: go

      - name: clone code into the Go module directory
        uses: actions/checkout@v2

      - name: install dependencies
        run: go mod download

      - name: compile Build
        run: make dev-build

  tests:
    name: tests
    runs-on: golang-1.14
    steps:
      - name: clone code into the Go module directory
        uses: actions/checkout@v2

      - name: install dependencies
        run: go mod download

      - name: test units
        run: make test-unit

      - name: test e2e
        run: make test-e2e

  linter:
    name: lint
    runs-on: golang-1.14
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
